// This file is automatically generated at compile-time to include a user created header file.
#define UE_DIRECT_HEADER_COMPILE 1
#define __COMPILING_MyActor
#include "C:/hello_world/hello/Source/hello/Public/MyActor.h"
